### ISSUE TITLE
Some confusion getting started using for the first time

### ISSUE THREAD

**Issue by jdiamond** [saibotsivad/mongodb-local-data-api#2]
Hello,

My team is considering using the Data API and wanted to know if there was an option for local development and so I came across your project. Thank you for releasing it. 

I ran into some issues while trying it out:

The README made me think I had to use the `setup` function which didn't make sense to me, but I eventually got a query to work with curl after studying the source code. Would have been nice if the README showed an example using curl and then I think some of my confusion would have been minimized.

Had to look in the code to see the URLs should start with /action instead of the longer URLs in the examples in the Data API docs. I think this is OK because we can configure any base URL we want and just append /find, /insertOne, etc.

Did not know what to put in `dataSource` until I saw the code that said it was ignored.

Only POST requests seem to work but some of the examples in the official docs show GET requests. Also not a big deal but was getting not found errors until I realized this.

When my local MongoDB doesn't require a username or password, omitting those options doesn't work. Using a simple `--url` option without username and password in the URL works, though.

Sending `Accept: application/ejson` seems to return the same data as application/json. I don't know yet if we will want to use ejson but I'm guessing you don't in your projects since it's not implemented?

In the end, I got it working so it's very nice to have the option of using your tool. I know I could have submitted multiple issues but didn't want to spam you.

I have a question. Do you use this on projects for work and find it valuable? I think I'd be OK with just using Atlas but I like having options, too, and don't want to prevent anybody from developing offline if they want to.

Thanks again.

**Comment by saibotsivad** [comment]
Thanks for the feedback! I'll do some work on the docs (and maybe some patches to the code) here over the next week or so, to make those things clearer.

> Do you use this on projects for work and find it valuable?

Yes, absolutely! Your concern (developing offline) is exactly why I landed on MongoDB Atlas (with their Data API) and this library.

The project(s) I'm using this for are private, but I can share the relevant parts for local development:

## MongoDB local

You might not need this, but I end up using DynamoDB, S3, and MongoDB (business apps) and so it made sense in my use case to containerize all these inside a Docker instance.

Using `docker compose` I ended up with something like this (only the MongoDB stuff):

```yaml
# $REPO/docker/docker-compose.yaml
version: '3.8'
services:
  mongodb-local:
    image: mongo:5.0
    ports:
      - "27017:27017"
    command: mongod --quiet --logpath /dev/null
    environment:
      - MONGO_INITDB_ROOT_USERNAME=LocalRootUser
      - MONGO_INITDB_ROOT_PASSWORD=c0bbf9da
    volumes:
      - "./mongodb:/data/db"
```

In case Docker isn't familiar (or for others who come across this), [install Docker](https://www.docker.com/products/docker-desktop), `cd` into your folder (in this example `$REPO/docker`) and run `docker-compose up`.

## MongoDB Local Data API

In my root repo I have a `package.json` which has these relevant parts:

```json
{
  "scripts": {
    "local": "run-p local:*",
    "local:docker": "cd deploy && docker compose up",
    "local:mongodb-data-api": "mongodb-local-data-api --username=LocalRootUser --password=c0bbf9da --apiKey=aaaabbbb111122223333 --apiPort=3007"
  },
  "devDependencies": {
    "mongodb-local-data-api": "^0.0.9",
    "npm-run-all": "^4.1.5"
  }
}
```

Make sure you use whatever the latest versions are, of course 😆

## Persisting MongoDB Data

The main thing is really that `volumes` property in the Docker YAML file, that has `"./mongodb:/data/db"` so that ends up being the folder `$REPO/docker/mongodb` is mapped to the Docker container `/data/db` folder.

If you do that, the MongoDB data will persist in your repo (need a gitignore entry) so that you don't lose data between restarts, and you can blow away that folder if you ever need a fresh start.

## Within the Application

For my applications, I just pass in environment variables to define the Data API parameters, so I have a "service" that I instantiate something like this:

```js
import { mongodb as initializeMongodb } from '@saibotsivad/mongodb'

export const mongodb = options => {
	const db = initializeMongodb({
		apiUrl: options.get('MONGODB_API_URL'),
		apiKey: options.get('MONGODB_API_KEY'),
		cluster: options.get('MONGODB_CLUSTER_NAME'),
		database: options.get('MONGODB_DATABASE_NAME'),
		collection: options.get('MONGODB_COLLECTION_NAME'),
		fetch: fetching,
	})
	// if you don't need this, you'd just return `db` directly and tidy up the function
	const wrapped = {}
	for (const key in db) wrapped[key] = async (...parameters) => {
		const out = await db[key](...parameters)
		// some logging stuff here based on response times and so on
		return out
	}
	return wrapped
}
```

## Closing Remarks

The rough architecture stack I have goes from Cloudflare Workers <-> MongoDB Atlas, along with many other bits and pieces of course 😅 

I use this library for local development for all projects, so it sees regular use.

At the moment there aren't really other people using it, as far as I'm aware, so I've had [some instances](https://github.com/saibotsivad/mongodb-local-data-api/blob/main/CHANGELOG.md#006---2022-02-10) where a particular method wasn't implemented correctly, and I didn't notice because I didn't use it. (I haven't got around to `aggregate` yet, so that one might need a patch.)

The last thing to note is, back when I made this their Data API had been in beta. Looking at their docs now, it seems like it is no longer beta?

I will probably spend some time over the next couple weeks to make sure all endpoints behave exactly the same, but if you notice any differences it would be great if you would open a new issue for each one! (Lots of filed issues is easier to handle than one big one, for me.)

**Comment by saibotsivad** [comment]
One last note about this comment

> the URLs should start with /action

From the docs, for example in [findOne](https://www.mongodb.com/docs/atlas/api/data-api-resources/#find-a-single-document), their example says to use `POST /action/findOne` and then for their example they have:

```
https://data.mongodb-api.com/app/<Data API App ID>/endpoint/data/v1/action/findOne
```

My  goal here was to create as close to an identical experience as possible for the locally running API, so (if I made it correctly...) you should access that locally with the URL like this (assuming port 3000):

```
http://localhost:3000/app/<Data API App ID>/endpoint/data/v1/action/findOne
```

I'll try to document that a bit clearer, and thanks for the `cURL` suggestion, that will probably make it more obvious! 👍

**Comment by jdiamond** [comment]
Thanks so much for the detailed response.

We do use Docker and Docker Compose for our databases and map volumes like you described. Nice to see your setup, though, as it gives me some ideas. I should have looked at your other repositories to see your wrapper around the Data API as that also looks very useful.

I checked my notes and I definitely only used /action/find in my URL to the local Data API service and I'm sure it worked. Maybe it's because I didn't use the `--apiKey` option? Will try again by following your example.

In the future, I will make separate issues if I find any. We do use aggregate heavily in our existing codebase and I assume we will continue to in this new project so, if it doesn't work, I will see about making a PR.

Thanks again for the great code and feedback.
